### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by lzblack** [ctnicholson/team_project#1]
In general, I like this idea. 

1. What is the API for? If you just need to update scores/ranking based on real game result, only one request is needed (for every game). Consider storing game results in a database or a flat file.
2. What will be the scoring mechanism?

**Comment by bfunk1** [comment]
Hi Professor,

We will follow your advice and update according to game updates and store that in a database. As for the scoring mechanism, it will be based on points allocated to users based on predicting the winning team and a bonus for closeness to guessing the score.
